# Generated by Django 5.1.3 on 2025-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_time', models.DateTimeField()),
                ('number_people', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to='restaurants/', verbose_name='Resized Image')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating')),
                ('reviews', models.PositiveIntegerField(default=0, verbose_name='Number of Reviews')),
                ('available_sites', models.PositiveIntegerField(verbose_name='Available sites')),
                ('opening_hours', models.JSONField(verbose_name='Opening Hours')),
                ('closed_days', models.JSONField(blank=True, null=True, verbose_name='Closed Days')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
    ]
